Remove further instances of writing to /dev/stderr

diff --git a/pcawg/irap_pcawg_align b/pcawg/irap_pcawg_align
--- a/pcawg/irap_pcawg_align
+++ b/pcawg/irap_pcawg_align
@@ -10,7 +10,7 @@ DATA_TOPLEVEL_DIR=test_data
 metadata_file=$DATA_TOPLEVEL_DIR/metadata.tsv
 
 if [ "$id-" == "-" ]; then
-   echo "Usage: irap_pcawg_align  SOP tar.gz ID" > /dev/stderr
+   echo "Usage: irap_pcawg_align  SOP tar.gz ID"  1>&2
    exit 1
 fi
 
@@ -26,7 +26,7 @@ if [ "$tarball-" == "-" ]; then
 fi
 
 if [ ! -e $tarball ]; then
-   echo "$tarball not found" > /dev/stderr
+   echo "$tarball not found"  1>&2
    exit 1
 fi
 
diff --git a/scripts/fastqc2tsv b/scripts/fastqc2tsv
--- a/scripts/fastqc2tsv
+++ b/scripts/fastqc2tsv
@@ -8,11 +8,11 @@ zip=y
 ifile=$1
 cat_cmd="unzip -p $ifile"
 if [ ! -e $ifile ] ; then
-   echo "$ifile not found" > /dev/stderr
+   echo "$ifile not found"  1>&2
    zip=n	
    ifile=`echo $ifile|sed "s/.fastqc.zip/_fastqc/"`
    if [ ! -e $ifile ] ; then 
-      echo "$ifile not found" > /dev/stderr	
+      echo "$ifile not found"  1>&2	
       exit 1
    fi   
    cat_cmd=cat		
