Manual undo last commits

diff --git a/scripts/irap_lsf b/scripts/irap_lsf
--- a/scripts/irap_lsf
+++ b/scripts/irap_lsf
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # =========================================================
-# Copyright 2012-2017,  Nuno A. Fonseca (nuno dot fonseca at gmail dot com)
+# Copyright 2012-2018,  Nuno A. Fonseca (nuno dot fonseca at gmail dot com)
 #
 # This file is part of iRAP.
 #
@@ -24,13 +24,12 @@
 #Output: send jobs on the farm
 set -e 
 function stop_now {
-    cur_status=$1
-    shift 1
-    wf1=$1
-    shift 1
+    cur_level=$1
+    wfc=$2
+    shift 2
     pend=$*
-    if [ "$wave-" == "$cur_status-" ]; then
-	final_job $pend $wf1
+    if [ "$wave-" == "$cur_level-" ]; then
+	final_job $pend $wfc $cur_level
 	exit
     fi
 }
@@ -39,19 +38,27 @@ function usage {
     echo "irap_lsf [-s -l level] irap options"
 }
 ###################################
-level=6
+level=5
 irap_cmd=irap
+DEBUG=0
 
+# DEBUG=1 - prints all lsf commands
+# DEBUG=2 - prints all irap commands
 
-while getopts "l:s"  Option; do
+while getopts "l:sdD"  Option; do
     case $Option in
 	s ) irap_cmd=irap_sc;;
         l ) level=$OPTARG;;
+	d ) DEBUG=1;;
+	D ) DEBUG=2;;
 	h) usage; exit;;
     esac
 done
 
 shift $((OPTIND-1))
+if [ "$DEBUG-" != "0-" ]; then
+    echo "DEBUG enabled ($DEBUG)"
+fi
 echo $*
 
 
@@ -64,25 +71,51 @@ cmd="$irap_cmd "
 
 wave=$level
 set +e
-$cmd conf=$conf $IRAP_PARAMS -n -q
 
-if [ $? -eq 0 ]; then
+
+echo "Checking current status..."
+$cmd conf=$conf $IRAP_PARAMS -n -q
+let ret=$?
+if [ $ret -eq 0 ]; then
     echo "All done - no need to submit jobs"
     exit 0
 fi
+if [ $ret -eq 1 ]; then
+    echo "Starting job submission..."
+else
+    echo "ERROR: please run"
+    echo "$cmd conf=$conf $IRAP_PARAMS quickcheck -n -q"
+    echo "before runnig irap_lsf and address the error messages"
+    exit 1
+fi
+echo "Starting job submission..."
 
+wfb=`irap_init_job|tail -n 1`
+wf0=`submit_jobs4stage $wfb 0|tail -n 1`
+stop_now 0 $wfb $wf0
+wf1=`submit_jobs4stage $wf0 1|tail -n 1`
+stop_now 1 $wfb $wf1
+wf2=`submit_jobs4stage $wf1 2|tail -n 1`
+stop_now 2 $wfb $wf2
+# if [ "$level-" == "1-" ]; then
+#     wf3=`stage1_jobs $wf2|tail -n 1`
+#     stop_now 1  $wf1 $wf3
+# else
+#     if [ "$level-" == "2-" ]; then
+# 	wf3=`stage12_jobs $wf2|tail -n 1`
+# 	stop_now 2  $wf1 $wf3
+#     else
+# 	wf3=`stage123_jobs $wf2|tail -n 1`
+#     fi
+# fi
 
-wf1=`irap_init_job|tail -n 1`
-wf2=`stage0_jobs $wf1|tail -n 1`
-stop_now 0 $wf1 $wf2
-wf3=`stage123_jobs $wf2|tail -n 1`
-stop_now 2  $wf1 $wf3
-wf4=`stage3_jobs $wf3|tail -n 1`
-stop_now 3 $wf1 $wf4
-wf5=`stage4_jobs $wf4|tail -n 1`
-stop_now 4 $wf1 $wf5
-wf6=`stage5_jobs $wf5 |tail -n 1`
+wf3s=`submit_jobs4stage $wf2 3_s|tail -n 1`
+wf3=`submit_jobs4stage $wf3s 3|tail -n 1`
+stop_now 3 $wfb $wf3
+wf4=`submit_jobs4stage $wf3 4|tail -n 1`
+stop_now 4 $wfb $wf4
+wf5=`submit_jobs4stage $wf4 5 |tail -n 1`
 
-final_job $wf6 $wf1
+final_job $wf5 $wf1 5
 exit
 
