Files cleanup

diff --git a/scripts/irap_single_lib b/scripts/irap_single_lib
--- a/scripts/irap_single_lib
+++ b/scripts/irap_single_lib
@@ -9,16 +9,18 @@ mem=4000000000
 threads=1
 irap_options=
 do_stage0=no
+do_clean=n
 run_faster=n
 # This script will not run with sudo
 # http://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied
 STDERR=/dev/stderr
 
+#################################################################
 #
 function print_usage {
 cat <<EOF
 iRAP wrapper to process a single library
-Usage: irap_single_lib -1 fastq_file [-2 fastq_file2] -c irap.configuration  [-s strand (first,second,both)] [-m MEM] [-t threads] [-i irap_options] [-0] [-h]
+Usage: irap_single_lib -1 fastq_file [-2 fastq_file2] -c irap.configuration  [-s strand (first,second,both)] [-m MEM] [-t threads] [-i irap_options] [-0] [-h] [-C]
 
 -0  - should be executed once for each
 species/genome/annotation to generate the indexes and other files
@@ -26,6 +28,7 @@ necessary for the analysis.
 
 -m MEM - value in bytes
 
+-C full clean up
 
 EOF
 }
@@ -103,15 +106,16 @@ function run_AND_timeIt {
     #/usr/bin/time -o $logfile -a --format "$label\t%E\t%e\t%M\t$datetime" $*
     #echo "EXIT:$?" > /dev/stderr
 }
-################################################
+#################################################################
 # 
-while getopts "1:2:c:s:m:t:i:h0f"  Option
+while getopts "1:2:c:s:m:t:i:h0fC"  Option
 do
     case $Option in
 	0 ) do_stage0="yes";;
         1 ) f1=$OPTARG;;
         2 ) f2=$OPTARG;;# send all output to a log file
         c ) conf=$OPTARG;;# send all output to a log file
+	C ) do_clean=y;;
 	s ) strand=$OPTARG;;# send all output to a log file
 	m ) mem=$OPTARG;;
 	t ) threads=$OPTARG;;
@@ -185,7 +189,7 @@ fi
 
 set -e
 
-################################################
+##################################################################
 # place the tarball in the right folder
 DATA_DIR=`get_data_dir`
 pinfo "Data dir.=$DATA_DIR"
@@ -195,7 +199,7 @@ TARGET_DIR=$DATA_DIR/raw_data/single_lib/$folder
 
 mkdir -p $TARGET_DIR
 
-################################################
+##################################################################
 # put the fastq files in the "expected" folder
 pushd $TARGET_DIR > /dev/null 
 pinfo "Unpacking fastq files to $TARGET_DIR"
@@ -217,14 +221,15 @@ fi
 pinfo "FASTQ files in place"
 popd > /dev/null 
 
-################################################
+#################################################################
 odir=$PWD/out/`dirname $f1|cut -f 2- -d /`
 fileprefix=`get_fileprefix $f1`
 pinfo "Final files will be placed in $odir"
 if [ ! -e  $odir ]; then
     mkdir -p $odir
 fi
-################################################
+
+#################################################################
 # TSV with the time and memory used
 time_log_file=$odir/`get_fileprefix $f1`.time
 pinfo "Time log file in $time_log_file"
@@ -245,7 +250,7 @@ if [ $? !=  0 ]; then
     fi
 fi
 
-################################################
+#################################################################
 # run fastq_info on the file
 set -e
 pinfo "Validating FASTQ files..."
@@ -287,9 +292,12 @@ popd
 INFO_FILE=$TARGET_DIR/$f1_bn.info
 
 set +e
-########################################################
+
+irap_single_lib_options="conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE max_mem=$mem max_threads=$threads raw_folder=single_lib "
+
+##################################################################
 pinfo "QC and filtering..."
-run_AND_timeIt "iRAP-QC" $time_log_file  irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options max_mem=$mem max_threads=$threads raw_folder=single_lib stage1
+run_AND_timeIt "iRAP-QC" $time_log_file  irap $irap_single_lib_options $irap_options stage1
 if [ $? != 0 ]; then
     perror "iRAP failed"
     exit 1
@@ -297,7 +305,7 @@ fi
 pinfo "QC and filtering...complete."
 
 pinfo "Aligning data..."
-run_AND_timeIt "iRAP-Mapping" $time_log_file  irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options max_mem=$mem max_threads=$threads raw_folder=single_lib stage2
+run_AND_timeIt "iRAP-Mapping" $time_log_file  irap $irap_single_lib_options $irap_options stage2
 if [ $? != 0 ]; then
     perror "iRAP failed"
     exit 1
@@ -305,31 +313,38 @@ fi
 pinfo "Aligning data...complete."
 
 pinfo "Quantification..."
-run_AND_timeIt "iRAP-Quant" $time_log_file  irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options max_mem=$mem max_threads=$threads raw_folder=single_lib stage3as
+run_AND_timeIt "iRAP-Quant" $time_log_file  irap $irap_single_lib_options $irap_options stage3as
 if [ $? != 0 ]; then
     perror "iRAP failed"
     exit 1
 fi
 pinfo "Quantification...complete."
 
-
+#################################################################
 pinfo "Mapping QC..."
 # report files
-REPORT_TSVs=`irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options print_mapping_report_req  |tail -n 1`
-run_AND_timeIt "iRAP-Mapping-QC" $time_log_file  irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options max_mem=$mem max_threads=$threads raw_folder=single_lib $REPORT_TSVs
+REPORT_TSVs=`irap $irap_single_lib_options  $irap_options print_mapping_report_req  |tail -n 1`
+run_AND_timeIt "iRAP-Mapping-QC" $time_log_file  irap $irap_single_lib_options $irap_options  $REPORT_TSVs
 if [ $? != 0 ]; then
     perror "iRAP failed"
     exit 1
 fi
 pinfo "Mapping QC...complete."
 
-set -e
 
-# BAM
-BAM=`irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options print_stage2_files|tail -n 1`
+#################################################################
+# BAM->CRAM
+set -e
+BAM=`irap $irap_single_lib_options $irap_options print_stage2_files|tail -n 1`
 if [ ! -e "$BAM" ]; then
-    perror "Ooops: $BAM not found"
+    perror "Ooops: $BAM not found! This is not good :("
     exit 1
+fi
+
+CRAM_FILE=`dirname $odir/$f1_bn`/$libname_noprefix.cram    
+set +e
+if [ $run_faster=="y" ] && [ -e $CRAM_FILE ] && [ -e $CRAM_FILE.md5 ] ; then
+    pinfo "$CRAM_FILE exists - skipping generation of CRAM file. Do not use -f option to force the generation of the CRAM file."
 else
     # cp while in devel 
     #mv $BAM $odir/$f1_bn.bam
@@ -339,40 +354,47 @@ else
     
     # create the CRAM file
     pinfo "CRAMMING..."
-    run_AND_timeIt "iRAP-CRAM" $time_log_file  irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options max_mem=$mem max_threads=$threads raw_folder=single_lib $odir/$f1_bn.cram
+    run_AND_timeIt "iRAP-CRAM" $time_log_file  irap $irap_single_lib_options $irap_options  $odir/$f1_bn.cram
     if [ $? != 0 ]; then
 	perror "Generation of CRAM file failed"
 	exit 1
     fi
     pinfo "CRAMMING...done."
-    CRAM_FILE=`dirname $odir/$f1_bn`/$libname_noprefix.cram    
+
     mv $odir/$f1_bn.cram $CRAM_FILE
     pinfo "CRAM_FILE created"
     # generate the md5sum
     md5sum $CRAM_FILE > $CRAM_FILE.tmp.md5 && mv $CRAM_FILE.tmp.md5 $CRAM_FILE.md5
     pinfo "$CRAM_FILE.md5 created"
     rm -f $odir/$f1_bn.bam
-    pinfo "BAM file deleted"
+    pinfo "Temporary BAM file deleted"
 fi
 
 # 
-TSVs=`irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options print_stage3_s_targets  |tail -n 1`
+TSVs=`irap $irap_single_lib_options  $irap_options print_stage3_s_targets  |tail -n 1`
 
 pinfo "Moving the following files to $odir: $TSVs $REPORT_TSVs"
-cp $TSVs $odir
+cp -a $TSVs $odir
 #mv $TSVs $odir
 
 # report files
-#REPORT_TSVs=`irap conf=$conf data_dir=$DATA_DIR $libs lib.info=$INFO_FILE $irap_options print_mapping_report_req  |tail -n 1`
-cp $REPORT_TSVs $odir
+cp -a $REPORT_TSVs $odir
 # rename the files (remove the l prefix added by fastq_info)
-
 rename $libname $libname_noprefix `dirname $odir/$f1_bn`/$libname*
 
 # copy the info file
 cp $INFO_FILE $odir
-# 
-# test1/tophat1/htseq2/genes.rpkm.deseq.tsv.tmp
 pinfo "Files in $odir"
+
+#################################################################
+# Cleanup
+if [ "$do_clean" == "y" ]; then
+    pinfo "Full clean up..."
+    run_AND_timeIt "iRAP-tidyup" $time_log_file  irap $irap_single_lib_options $irap_options lib_full_clean
+    pinfo "Full clean up...done."
+else
+    run_AND_timeIt "iRAP-tidyup" $time_log_file  irap $irap_single_lib_options $irap_options clean
+fi
+
 pinfo "All done."
 exit 0
