Fixed: added missing '\0'. Minor fixes.
Former-commit-id: 218359a601442b887fe3259227b71240aa693c90 [formerly fa3af9a139e41570a44edae9a71fbdd918a477d8]
Former-commit-id: 8ea40d546e0e5dc8e944711719776862cbd9f37b

diff --git a/src/fastq_utils/Makefile b/src/fastq_utils/Makefile
--- a/src/fastq_utils/Makefile
+++ b/src/fastq_utils/Makefile
@@ -82,14 +82,14 @@ test6:
 	./fastq_validator tests/test_e8.fastq || \
 	./fastq_validator tests/test_e9.fastq || \
 	./fastq_validator tests/test_e10.fastq || \
-	echo "all errors detected"
+	echo "OK! all errors detected"
 	./fastq_validator tests/test_1.fastq
 	./fastq_validator tests/test_2.fastq
 	./fastq_validator tests/test_e11.fastq
 	time -p ./fastq_validator tests/pe_bug14.fastq tests/pe_bug14.fastq
 	time -p ./fastq_validator tests/c18_1M_1.fastq
 	time -p ./fastq_validator tests/c18_1M_2.fastq
-	time -p ./fastq_validator tests/c18_1M_1.fastq tests/c18_1M_2.fastq || echo "Error detected"
+	time -p ./fastq_validator tests/c18_1M_1.fastq tests/c18_1M_2.fastq || echo "OK! Error detected"
 
 
 tests: test1 test2 test3 test4 test5 test6
